<a href="https://colab.research.google.com/github/Arunimacs/Machine-Learning-works/blob/main/working_with_json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. working with json**

In [ ]:
#Reading json file
import pandas as pd
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
#head parameter displays the specified number of rows only.
s=pd.read_json('train.json')
s.head(1000)

        id       cuisine                                        ingredients
0    10259         greek  [romaine lettuce, black olives, grape tomatoes...
1    25693   southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2    20130      filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3    22213        indian                [water, vegetable oil, wheat, salt]
4    13162        indian  [black pepper, shallots, cornflour, cayenne pe...
..     ...           ...                                                ...
995   5964       italian  [tomato sauce, extra-virgin olive oil, grated ...
996  30297        korean                         [water, medium-grain rice]
997   3037       mexican  [eggs, grating cheese, jalapeno chilies, fresh...
998  19712  cajun_creole  [andouille sausage, butter, garlic cloves, dri...
999   4400         greek  [ground black pepper, extra-virgin olive oil, ...

[1000 rows x 3 columns]

In [ ]:
#Reading json file from an api url.
pd.read_json('https://v6.exchangerate-api.com/v6/0416107a045be96d2f1a8908/latest/USD')

,result,documentation,terms_of_use,time_last_update_unix,time_last_update_utc,time_next_update_unix,time_next_update_utc,base_code,conversion_rates
USD,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,1.0000
AED,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,3.6725
AFN,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,64.9519
ALL,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,81.5232
AMD,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,359.9763
...,...,...,...,...,...,...,...,...,...
YER,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,236.0415
ZAR,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,16.6724
ZMW,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,20.2478
ZWG,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,26.5714
ZWL,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1793404801,"Sat, 31 Oct 2026 00:00:01 +0000",1793491201,"Sun, 01 Nov 2026 00:00:01 +0000",USD,26.5714