In [1]:
import pandas as pd

In [2]:
import mysql.connector

In [4]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [8]:
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\aruni\AppData\Local\Temp\ipykernel_2808\374620591.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [7]:
pd.read_sql_query("SELECT * FROM City WHERE CountryCode LIKE 'IND'",conn)

C:\Users\aruni\AppData\Local\Temp\ipykernel_2808\1076323297.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM City WHERE CountryCode LIKE 'IND'",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [9]:
pd.read_sql_query("SELECT * FROM City WHERE CountryCode LIKE 'USA'",conn)

C:\Users\aruni\AppData\Local\Temp\ipykernel_2808\2583377990.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM City WHERE CountryCode LIKE 'USA'",conn)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]

In [10]:
pd.read_sql_query("SELECT * FROM City WHERE District LIKE 'Gujarat'",conn)

C:\Users\aruni\AppData\Local\Temp\ipykernel_2808\2065745797.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM City WHERE District LIKE 'Gujarat'",conn)

      ID               Name CountryCode District  Population
0   1029          Ahmedabad         IND  Gujarat     2876710
1   1035              Surat         IND  Gujarat     1498817
2   1040  Vadodara (Baroda)         IND  Gujarat     1031346
3   1067             Rajkot         IND  Gujarat      559407
4   1090          Bhavnagar         IND  Gujarat      402338
5   1099           Jamnagar         IND  Gujarat      341637
6   1185             Nadiad         IND  Gujarat      167051
7   1241   Bharuch (Broach)         IND  Gujarat      133102
8   1245           Junagadh         IND  Gujarat      130484
9   1251            Navsari         IND  Gujarat      126089
10  1264        Gandhinagar         IND  Gujarat      123359
11  1266            Veraval         IND  Gujarat      123000
12  1283          Porbandar         IND  Gujarat      116671
13  1294              Anand         IND  Gujarat      110266
14  1313      Surendranagar         IND  Gujarat      105973
15  1317         Gandhidham         IND  Gujarat      104585
16  1322               Bhuj         IND  Gujarat      102176
17  1341             Godhra         IND  Gujarat       96813
18  1345              Patan         IND  Gujarat       96109
19  1362              Morvi         IND  Gujarat       90357
20  1364           Vejalpur         IND  Gujarat       89053

In [11]:
pd.read_sql_query("SELECT * FROM country",conn)

C:\Users\aruni\AppData\Local\Temp\ipykernel_2808\858535147.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [13]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy>60",conn)

C:\Users\aruni\AppData\Local\Temp\ipykernel_2808\89348110.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy>60",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the United States,US Territory,George W. Bush,4067,VI
163,VNM,Vietnam,Asia,Southeast Asia,331689.0,1945.0,79832000,69.3,21929.0,22834.0,Viêt Nam,Socialistic Republic,Trân Duc Luong,3770,VN
164,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537,VU
165,WSM,Samoa,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169,WS
166,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792,YU